# -*- coding: utf-8 -*-
# vim: ft=yaml
---
driver:
  name: vagrant

provisioner:
  name: salt_solo
  is_file_root: true
  state_top:
    base:
      "*":
        - test.mockup
        - stunnel

platforms:
  - name: bento/debian-8.8

suites:
  - name: default

  - name: custom
    provisioner:
      pillars-from-files:
        stunnel.sls: pillar_custom.sls
      pillars:
        top.sls:
          base:
            "*":
              - stunnel
